(princ "Quite something you've got there.")
(let ((x 8)
      (y 4))
  (terpri)
  (write x)
  (terpri)
  (write y)
  (terpri)
  (princ "Here's the sum of both the variables: ")
  (setq z (+ x y))
  (write z)
  (terpri)
  (princ "Here's the difference of both the variables: ")
  (setq z (- x y))
  (write z)
  (terpri)
  (princ "Here's the product of both the variables: ")
  (setq z (* x y))
  (write z)
  (terpri)
  (princ "Here's the division result of both the variables: ")
  (setq z (/ x y))
  (write z)
  )
